name: Check Live Subdomains

on:
  workflow_dispatch:
  push:
    paths:
      - 'subdomains.txt'

jobs:
  check-live-subdomains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install httx
        run: |
          curl -sL https://github.com/projectdiscovery/httx/releases/latest/download/httx-linux-amd64.tar.gz -o httx.tar.gz
          tar -xzf httx.tar.gz httx
          chmod +x httx
          sudo mv httx /usr/local/bin/

      - name: Run httx on subdomains
        run: |
          cat subdomains.txt | httx -silent > live-subdomains.txt
          echo "✅ Found $(wc -l < live-subdomains.txt) live subdomains."

      - name: Upload live subdomains as artifact
        uses: actions/upload-artifact@v4
        with:
          name: live-subdomains
          path: live-subdomains.txt
