name: Post New Nuclei Template to Twitter

on:
  schedule:
    - cron: "0 * * * *"  # Runs every 1 hour at minute 0
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Git to Rebase Upstream
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote add upstream https://github.com/projectdiscovery/nuclei-templates.git
          git fetch upstream
          git rebase upstream/main
          git push origin main --force

  tweet:
    runs-on: ubuntu-latest
    needs: sync-fork
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tweepy

      - name: Run tweet.py Script
        run: python tweet.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
